#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAAddIn.Applications.SQLServerScriptGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EA_Release1")]
	public partial class SystemTablesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SystemTablesDataContext() : 
				base(global::EAAddIn.Properties.Settings.Default.EA_Release1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SystemTablesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemTablesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemTablesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemTablesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<column> columns
		{
			get
			{
				return this.GetTable<column>();
			}
		}
		
		public System.Data.Linq.Table<table> tables
		{
			get
			{
				return this.GetTable<table>();
			}
		}
		
		public System.Data.Linq.Table<type> types
		{
			get
			{
				return this.GetTable<type>();
			}
		}
		
		public System.Data.Linq.Table<@object> objects
		{
			get
			{
				return this.GetTable<@object>();
			}
		}
		
		public System.Data.Linq.Table<procedure> procedures
		{
			get
			{
				return this.GetTable<procedure>();
			}
		}
		
		public System.Data.Linq.Table<index> indexes
		{
			get
			{
				return this.GetTable<index>();
			}
		}
		
		public System.Data.Linq.Table<index_column> index_columns
		{
			get
			{
				return this.GetTable<index_column>();
			}
		}
		
		public System.Data.Linq.Table<foreign_key> foreign_keys
		{
			get
			{
				return this.GetTable<foreign_key>();
			}
		}
		
		public System.Data.Linq.Table<foreign_key_column> foreign_key_columns
		{
			get
			{
				return this.GetTable<foreign_key_column>();
			}
		}
		
		public System.Data.Linq.Table<key_constraint> key_constraints
		{
			get
			{
				return this.GetTable<key_constraint>();
			}
		}
		
		public System.Data.Linq.Table<check_constraint> check_constraints
		{
			get
			{
				return this.GetTable<check_constraint>();
			}
		}
		
		public System.Data.Linq.Table<default_constraint> default_constraints
		{
			get
			{
				return this.GetTable<default_constraint>();
			}
		}
		
		public System.Data.Linq.Table<trigger> triggers
		{
			get
			{
				return this.GetTable<trigger>();
			}
		}
		
		public System.Data.Linq.Table<sql_module> sql_modules
		{
			get
			{
				return this.GetTable<sql_module>();
			}
		}
		
		public System.Data.Linq.Table<view> views
		{
			get
			{
				return this.GetTable<view>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.columns")]
	public partial class column
	{
		
		private int _object_id;
		
		private string _name;
		
		private int _column_id;
		
		private byte _system_type_id;
		
		private int _user_type_id;
		
		private short _max_length;
		
		private byte _precision;
		
		private byte _scale;
		
		private string _collation_name;
		
		private System.Nullable<bool> _is_nullable;
		
		private bool _is_ansi_padded;
		
		private bool _is_rowguidcol;
		
		private bool _is_identity;
		
		private bool _is_computed;
		
		private bool _is_filestream;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _is_non_sql_subscribed;
		
		private System.Nullable<bool> _is_merge_published;
		
		private System.Nullable<bool> _is_dts_replicated;
		
		private bool _is_xml_document;
		
		private int _xml_collection_id;
		
		private int _default_object_id;
		
		private int _rule_object_id;
		
		public column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column_id", DbType="Int NOT NULL")]
		public int column_id
		{
			get
			{
				return this._column_id;
			}
			set
			{
				if ((this._column_id != value))
				{
					this._column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_type_id", DbType="TinyInt NOT NULL")]
		public byte system_type_id
		{
			get
			{
				return this._system_type_id;
			}
			set
			{
				if ((this._system_type_id != value))
				{
					this._system_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this._user_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_length", DbType="SmallInt NOT NULL")]
		public short max_length
		{
			get
			{
				return this._max_length;
			}
			set
			{
				if ((this._max_length != value))
				{
					this._max_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precision", DbType="TinyInt NOT NULL")]
		public byte precision
		{
			get
			{
				return this._precision;
			}
			set
			{
				if ((this._precision != value))
				{
					this._precision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="TinyInt NOT NULL")]
		public byte scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this._scale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_nullable", DbType="Bit")]
		public System.Nullable<bool> is_nullable
		{
			get
			{
				return this._is_nullable;
			}
			set
			{
				if ((this._is_nullable != value))
				{
					this._is_nullable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padded", DbType="Bit NOT NULL")]
		public bool is_ansi_padded
		{
			get
			{
				return this._is_ansi_padded;
			}
			set
			{
				if ((this._is_ansi_padded != value))
				{
					this._is_ansi_padded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_rowguidcol", DbType="Bit NOT NULL")]
		public bool is_rowguidcol
		{
			get
			{
				return this._is_rowguidcol;
			}
			set
			{
				if ((this._is_rowguidcol != value))
				{
					this._is_rowguidcol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_identity", DbType="Bit NOT NULL")]
		public bool is_identity
		{
			get
			{
				return this._is_identity;
			}
			set
			{
				if ((this._is_identity != value))
				{
					this._is_identity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_computed", DbType="Bit NOT NULL")]
		public bool is_computed
		{
			get
			{
				return this._is_computed;
			}
			set
			{
				if ((this._is_computed != value))
				{
					this._is_computed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_filestream", DbType="Bit NOT NULL")]
		public bool is_filestream
		{
			get
			{
				return this._is_filestream;
			}
			set
			{
				if ((this._is_filestream != value))
				{
					this._is_filestream = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this._is_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_non_sql_subscribed", DbType="Bit")]
		public System.Nullable<bool> is_non_sql_subscribed
		{
			get
			{
				return this._is_non_sql_subscribed;
			}
			set
			{
				if ((this._is_non_sql_subscribed != value))
				{
					this._is_non_sql_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit")]
		public System.Nullable<bool> is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_dts_replicated", DbType="Bit")]
		public System.Nullable<bool> is_dts_replicated
		{
			get
			{
				return this._is_dts_replicated;
			}
			set
			{
				if ((this._is_dts_replicated != value))
				{
					this._is_dts_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_xml_document", DbType="Bit NOT NULL")]
		public bool is_xml_document
		{
			get
			{
				return this._is_xml_document;
			}
			set
			{
				if ((this._is_xml_document != value))
				{
					this._is_xml_document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml_collection_id", DbType="Int NOT NULL")]
		public int xml_collection_id
		{
			get
			{
				return this._xml_collection_id;
			}
			set
			{
				if ((this._xml_collection_id != value))
				{
					this._xml_collection_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_object_id", DbType="Int NOT NULL")]
		public int default_object_id
		{
			get
			{
				return this._default_object_id;
			}
			set
			{
				if ((this._default_object_id != value))
				{
					this._default_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rule_object_id", DbType="Int NOT NULL")]
		public int rule_object_id
		{
			get
			{
				return this._rule_object_id;
			}
			set
			{
				if ((this._rule_object_id != value))
				{
					this._rule_object_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.tables")]
	public partial class table
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private System.Nullable<int> _lob_data_space_id;
		
		private System.Nullable<int> _filestream_data_space_id;
		
		private int _max_column_id_used;
		
		private bool _lock_on_bulk_load;
		
		private System.Nullable<bool> _uses_ansi_nulls;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _has_replication_filter;
		
		private System.Nullable<bool> _is_merge_published;
		
		private System.Nullable<bool> _is_sync_tran_subscribed;
		
		private bool _has_unchecked_assembly_data;
		
		private System.Nullable<int> _text_in_row_limit;
		
		private System.Nullable<bool> _large_value_types_out_of_row;
		
		public table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lob_data_space_id", DbType="Int")]
		public System.Nullable<int> lob_data_space_id
		{
			get
			{
				return this._lob_data_space_id;
			}
			set
			{
				if ((this._lob_data_space_id != value))
				{
					this._lob_data_space_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filestream_data_space_id", DbType="Int")]
		public System.Nullable<int> filestream_data_space_id
		{
			get
			{
				return this._filestream_data_space_id;
			}
			set
			{
				if ((this._filestream_data_space_id != value))
				{
					this._filestream_data_space_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_column_id_used", DbType="Int NOT NULL")]
		public int max_column_id_used
		{
			get
			{
				return this._max_column_id_used;
			}
			set
			{
				if ((this._max_column_id_used != value))
				{
					this._max_column_id_used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lock_on_bulk_load", DbType="Bit NOT NULL")]
		public bool lock_on_bulk_load
		{
			get
			{
				return this._lock_on_bulk_load;
			}
			set
			{
				if ((this._lock_on_bulk_load != value))
				{
					this._lock_on_bulk_load = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_ansi_nulls", DbType="Bit")]
		public System.Nullable<bool> uses_ansi_nulls
		{
			get
			{
				return this._uses_ansi_nulls;
			}
			set
			{
				if ((this._uses_ansi_nulls != value))
				{
					this._uses_ansi_nulls = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this._is_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_replication_filter", DbType="Bit")]
		public System.Nullable<bool> has_replication_filter
		{
			get
			{
				return this._has_replication_filter;
			}
			set
			{
				if ((this._has_replication_filter != value))
				{
					this._has_replication_filter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit")]
		public System.Nullable<bool> is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sync_tran_subscribed", DbType="Bit")]
		public System.Nullable<bool> is_sync_tran_subscribed
		{
			get
			{
				return this._is_sync_tran_subscribed;
			}
			set
			{
				if ((this._is_sync_tran_subscribed != value))
				{
					this._is_sync_tran_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_unchecked_assembly_data", DbType="Bit NOT NULL")]
		public bool has_unchecked_assembly_data
		{
			get
			{
				return this._has_unchecked_assembly_data;
			}
			set
			{
				if ((this._has_unchecked_assembly_data != value))
				{
					this._has_unchecked_assembly_data = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text_in_row_limit", DbType="Int")]
		public System.Nullable<int> text_in_row_limit
		{
			get
			{
				return this._text_in_row_limit;
			}
			set
			{
				if ((this._text_in_row_limit != value))
				{
					this._text_in_row_limit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_large_value_types_out_of_row", DbType="Bit")]
		public System.Nullable<bool> large_value_types_out_of_row
		{
			get
			{
				return this._large_value_types_out_of_row;
			}
			set
			{
				if ((this._large_value_types_out_of_row != value))
				{
					this._large_value_types_out_of_row = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.types")]
	public partial class type
	{
		
		private string _name;
		
		private byte _system_type_id;
		
		private int _user_type_id;
		
		private int _schema_id;
		
		private System.Nullable<int> _principal_id;
		
		private short _max_length;
		
		private byte _precision;
		
		private byte _scale;
		
		private string _collation_name;
		
		private System.Nullable<bool> _is_nullable;
		
		private bool _is_user_defined;
		
		private bool _is_assembly_type;
		
		private int _default_object_id;
		
		private int _rule_object_id;
		
		public type()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_type_id", DbType="TinyInt NOT NULL")]
		public byte system_type_id
		{
			get
			{
				return this._system_type_id;
			}
			set
			{
				if ((this._system_type_id != value))
				{
					this._system_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this._user_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_length", DbType="SmallInt NOT NULL")]
		public short max_length
		{
			get
			{
				return this._max_length;
			}
			set
			{
				if ((this._max_length != value))
				{
					this._max_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precision", DbType="TinyInt NOT NULL")]
		public byte precision
		{
			get
			{
				return this._precision;
			}
			set
			{
				if ((this._precision != value))
				{
					this._precision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="TinyInt NOT NULL")]
		public byte scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this._scale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_nullable", DbType="Bit")]
		public System.Nullable<bool> is_nullable
		{
			get
			{
				return this._is_nullable;
			}
			set
			{
				if ((this._is_nullable != value))
				{
					this._is_nullable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_user_defined", DbType="Bit NOT NULL")]
		public bool is_user_defined
		{
			get
			{
				return this._is_user_defined;
			}
			set
			{
				if ((this._is_user_defined != value))
				{
					this._is_user_defined = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_assembly_type", DbType="Bit NOT NULL")]
		public bool is_assembly_type
		{
			get
			{
				return this._is_assembly_type;
			}
			set
			{
				if ((this._is_assembly_type != value))
				{
					this._is_assembly_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_object_id", DbType="Int NOT NULL")]
		public int default_object_id
		{
			get
			{
				return this._default_object_id;
			}
			set
			{
				if ((this._default_object_id != value))
				{
					this._default_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rule_object_id", DbType="Int NOT NULL")]
		public int rule_object_id
		{
			get
			{
				return this._rule_object_id;
			}
			set
			{
				if ((this._rule_object_id != value))
				{
					this._rule_object_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.objects")]
	public partial class @object
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		public @object()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.procedures")]
	public partial class procedure
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private bool _is_auto_executed;
		
		private System.Nullable<bool> _is_execution_replicated;
		
		private System.Nullable<bool> _is_repl_serializable_only;
		
		private System.Nullable<bool> _skips_repl_constraints;
		
		public procedure()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_executed", DbType="Bit NOT NULL")]
		public bool is_auto_executed
		{
			get
			{
				return this._is_auto_executed;
			}
			set
			{
				if ((this._is_auto_executed != value))
				{
					this._is_auto_executed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_execution_replicated", DbType="Bit")]
		public System.Nullable<bool> is_execution_replicated
		{
			get
			{
				return this._is_execution_replicated;
			}
			set
			{
				if ((this._is_execution_replicated != value))
				{
					this._is_execution_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_repl_serializable_only", DbType="Bit")]
		public System.Nullable<bool> is_repl_serializable_only
		{
			get
			{
				return this._is_repl_serializable_only;
			}
			set
			{
				if ((this._is_repl_serializable_only != value))
				{
					this._is_repl_serializable_only = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skips_repl_constraints", DbType="Bit")]
		public System.Nullable<bool> skips_repl_constraints
		{
			get
			{
				return this._skips_repl_constraints;
			}
			set
			{
				if ((this._skips_repl_constraints != value))
				{
					this._skips_repl_constraints = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.indexes")]
	public partial class index
	{
		
		private int _object_id;
		
		private string _name;
		
		private int _index_id;
		
		private byte _type;
		
		private string _type_desc;
		
		private System.Nullable<bool> _is_unique;
		
		private int _data_space_id;
		
		private System.Nullable<bool> _ignore_dup_key;
		
		private System.Nullable<bool> _is_primary_key;
		
		private System.Nullable<bool> _is_unique_constraint;
		
		private byte _fill_factor;
		
		private System.Nullable<bool> _is_padded;
		
		private System.Nullable<bool> _is_disabled;
		
		private System.Nullable<bool> _is_hypothetical;
		
		private System.Nullable<bool> _allow_row_locks;
		
		private System.Nullable<bool> _allow_page_locks;
		
		public index()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", DbType="Int NOT NULL")]
		public int index_id
		{
			get
			{
				return this._index_id;
			}
			set
			{
				if ((this._index_id != value))
				{
					this._index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="TinyInt NOT NULL")]
		public byte type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_unique", DbType="Bit")]
		public System.Nullable<bool> is_unique
		{
			get
			{
				return this._is_unique;
			}
			set
			{
				if ((this._is_unique != value))
				{
					this._is_unique = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_space_id", DbType="Int NOT NULL")]
		public int data_space_id
		{
			get
			{
				return this._data_space_id;
			}
			set
			{
				if ((this._data_space_id != value))
				{
					this._data_space_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ignore_dup_key", DbType="Bit")]
		public System.Nullable<bool> ignore_dup_key
		{
			get
			{
				return this._ignore_dup_key;
			}
			set
			{
				if ((this._ignore_dup_key != value))
				{
					this._ignore_dup_key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_primary_key", DbType="Bit")]
		public System.Nullable<bool> is_primary_key
		{
			get
			{
				return this._is_primary_key;
			}
			set
			{
				if ((this._is_primary_key != value))
				{
					this._is_primary_key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_unique_constraint", DbType="Bit")]
		public System.Nullable<bool> is_unique_constraint
		{
			get
			{
				return this._is_unique_constraint;
			}
			set
			{
				if ((this._is_unique_constraint != value))
				{
					this._is_unique_constraint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fill_factor", DbType="TinyInt NOT NULL")]
		public byte fill_factor
		{
			get
			{
				return this._fill_factor;
			}
			set
			{
				if ((this._fill_factor != value))
				{
					this._fill_factor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_padded", DbType="Bit")]
		public System.Nullable<bool> is_padded
		{
			get
			{
				return this._is_padded;
			}
			set
			{
				if ((this._is_padded != value))
				{
					this._is_padded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_disabled", DbType="Bit")]
		public System.Nullable<bool> is_disabled
		{
			get
			{
				return this._is_disabled;
			}
			set
			{
				if ((this._is_disabled != value))
				{
					this._is_disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_hypothetical", DbType="Bit")]
		public System.Nullable<bool> is_hypothetical
		{
			get
			{
				return this._is_hypothetical;
			}
			set
			{
				if ((this._is_hypothetical != value))
				{
					this._is_hypothetical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allow_row_locks", DbType="Bit")]
		public System.Nullable<bool> allow_row_locks
		{
			get
			{
				return this._allow_row_locks;
			}
			set
			{
				if ((this._allow_row_locks != value))
				{
					this._allow_row_locks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allow_page_locks", DbType="Bit")]
		public System.Nullable<bool> allow_page_locks
		{
			get
			{
				return this._allow_page_locks;
			}
			set
			{
				if ((this._allow_page_locks != value))
				{
					this._allow_page_locks = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.index_columns")]
	public partial class index_column
	{
		
		private int _object_id;
		
		private int _index_id;
		
		private int _index_column_id;
		
		private int _column_id;
		
		private byte _key_ordinal;
		
		private byte _partition_ordinal;
		
		private System.Nullable<bool> _is_descending_key;
		
		private System.Nullable<bool> _is_included_column;
		
		public index_column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", DbType="Int NOT NULL")]
		public int index_id
		{
			get
			{
				return this._index_id;
			}
			set
			{
				if ((this._index_id != value))
				{
					this._index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_column_id", DbType="Int NOT NULL")]
		public int index_column_id
		{
			get
			{
				return this._index_column_id;
			}
			set
			{
				if ((this._index_column_id != value))
				{
					this._index_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column_id", DbType="Int NOT NULL")]
		public int column_id
		{
			get
			{
				return this._column_id;
			}
			set
			{
				if ((this._column_id != value))
				{
					this._column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_key_ordinal", DbType="TinyInt NOT NULL")]
		public byte key_ordinal
		{
			get
			{
				return this._key_ordinal;
			}
			set
			{
				if ((this._key_ordinal != value))
				{
					this._key_ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partition_ordinal", DbType="TinyInt NOT NULL")]
		public byte partition_ordinal
		{
			get
			{
				return this._partition_ordinal;
			}
			set
			{
				if ((this._partition_ordinal != value))
				{
					this._partition_ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_descending_key", DbType="Bit")]
		public System.Nullable<bool> is_descending_key
		{
			get
			{
				return this._is_descending_key;
			}
			set
			{
				if ((this._is_descending_key != value))
				{
					this._is_descending_key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_included_column", DbType="Bit")]
		public System.Nullable<bool> is_included_column
		{
			get
			{
				return this._is_included_column;
			}
			set
			{
				if ((this._is_included_column != value))
				{
					this._is_included_column = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.foreign_keys")]
	public partial class foreign_key
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private System.Nullable<int> _referenced_object_id;
		
		private System.Nullable<int> _key_index_id;
		
		private bool _is_disabled;
		
		private bool _is_not_for_replication;
		
		private bool _is_not_trusted;
		
		private System.Nullable<byte> _delete_referential_action;
		
		private string _delete_referential_action_desc;
		
		private System.Nullable<byte> _update_referential_action;
		
		private string _update_referential_action_desc;
		
		private bool _is_system_named;
		
		public foreign_key()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_object_id", DbType="Int")]
		public System.Nullable<int> referenced_object_id
		{
			get
			{
				return this._referenced_object_id;
			}
			set
			{
				if ((this._referenced_object_id != value))
				{
					this._referenced_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_key_index_id", DbType="Int")]
		public System.Nullable<int> key_index_id
		{
			get
			{
				return this._key_index_id;
			}
			set
			{
				if ((this._key_index_id != value))
				{
					this._key_index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_disabled", DbType="Bit NOT NULL")]
		public bool is_disabled
		{
			get
			{
				return this._is_disabled;
			}
			set
			{
				if ((this._is_disabled != value))
				{
					this._is_disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_not_for_replication", DbType="Bit NOT NULL")]
		public bool is_not_for_replication
		{
			get
			{
				return this._is_not_for_replication;
			}
			set
			{
				if ((this._is_not_for_replication != value))
				{
					this._is_not_for_replication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_not_trusted", DbType="Bit NOT NULL")]
		public bool is_not_trusted
		{
			get
			{
				return this._is_not_trusted;
			}
			set
			{
				if ((this._is_not_trusted != value))
				{
					this._is_not_trusted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_referential_action", DbType="TinyInt")]
		public System.Nullable<byte> delete_referential_action
		{
			get
			{
				return this._delete_referential_action;
			}
			set
			{
				if ((this._delete_referential_action != value))
				{
					this._delete_referential_action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_referential_action_desc", DbType="NVarChar(60)")]
		public string delete_referential_action_desc
		{
			get
			{
				return this._delete_referential_action_desc;
			}
			set
			{
				if ((this._delete_referential_action_desc != value))
				{
					this._delete_referential_action_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_referential_action", DbType="TinyInt")]
		public System.Nullable<byte> update_referential_action
		{
			get
			{
				return this._update_referential_action;
			}
			set
			{
				if ((this._update_referential_action != value))
				{
					this._update_referential_action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_referential_action_desc", DbType="NVarChar(60)")]
		public string update_referential_action_desc
		{
			get
			{
				return this._update_referential_action_desc;
			}
			set
			{
				if ((this._update_referential_action_desc != value))
				{
					this._update_referential_action_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_system_named", DbType="Bit NOT NULL")]
		public bool is_system_named
		{
			get
			{
				return this._is_system_named;
			}
			set
			{
				if ((this._is_system_named != value))
				{
					this._is_system_named = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.foreign_key_columns")]
	public partial class foreign_key_column
	{
		
		private int _constraint_object_id;
		
		private int _constraint_column_id;
		
		private int _parent_object_id;
		
		private int _parent_column_id;
		
		private int _referenced_object_id;
		
		private int _referenced_column_id;
		
		public foreign_key_column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_constraint_object_id", DbType="Int NOT NULL")]
		public int constraint_object_id
		{
			get
			{
				return this._constraint_object_id;
			}
			set
			{
				if ((this._constraint_object_id != value))
				{
					this._constraint_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_constraint_column_id", DbType="Int NOT NULL")]
		public int constraint_column_id
		{
			get
			{
				return this._constraint_column_id;
			}
			set
			{
				if ((this._constraint_column_id != value))
				{
					this._constraint_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_column_id", DbType="Int NOT NULL")]
		public int parent_column_id
		{
			get
			{
				return this._parent_column_id;
			}
			set
			{
				if ((this._parent_column_id != value))
				{
					this._parent_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_object_id", DbType="Int NOT NULL")]
		public int referenced_object_id
		{
			get
			{
				return this._referenced_object_id;
			}
			set
			{
				if ((this._referenced_object_id != value))
				{
					this._referenced_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_column_id", DbType="Int NOT NULL")]
		public int referenced_column_id
		{
			get
			{
				return this._referenced_column_id;
			}
			set
			{
				if ((this._referenced_column_id != value))
				{
					this._referenced_column_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.key_constraints")]
	public partial class key_constraint
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private System.Nullable<int> _unique_index_id;
		
		private bool _is_system_named;
		
		public key_constraint()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unique_index_id", DbType="Int")]
		public System.Nullable<int> unique_index_id
		{
			get
			{
				return this._unique_index_id;
			}
			set
			{
				if ((this._unique_index_id != value))
				{
					this._unique_index_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_system_named", DbType="Bit NOT NULL")]
		public bool is_system_named
		{
			get
			{
				return this._is_system_named;
			}
			set
			{
				if ((this._is_system_named != value))
				{
					this._is_system_named = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.check_constraints")]
	public partial class check_constraint
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private bool _is_disabled;
		
		private bool _is_not_for_replication;
		
		private bool _is_not_trusted;
		
		private int _parent_column_id;
		
		private string _definition;
		
		private System.Nullable<bool> _uses_database_collation;
		
		private bool _is_system_named;
		
		public check_constraint()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_disabled", DbType="Bit NOT NULL")]
		public bool is_disabled
		{
			get
			{
				return this._is_disabled;
			}
			set
			{
				if ((this._is_disabled != value))
				{
					this._is_disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_not_for_replication", DbType="Bit NOT NULL")]
		public bool is_not_for_replication
		{
			get
			{
				return this._is_not_for_replication;
			}
			set
			{
				if ((this._is_not_for_replication != value))
				{
					this._is_not_for_replication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_not_trusted", DbType="Bit NOT NULL")]
		public bool is_not_trusted
		{
			get
			{
				return this._is_not_trusted;
			}
			set
			{
				if ((this._is_not_trusted != value))
				{
					this._is_not_trusted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_column_id", DbType="Int NOT NULL")]
		public int parent_column_id
		{
			get
			{
				return this._parent_column_id;
			}
			set
			{
				if ((this._parent_column_id != value))
				{
					this._parent_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_definition", DbType="NVarChar(MAX)")]
		public string definition
		{
			get
			{
				return this._definition;
			}
			set
			{
				if ((this._definition != value))
				{
					this._definition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_database_collation", DbType="Bit")]
		public System.Nullable<bool> uses_database_collation
		{
			get
			{
				return this._uses_database_collation;
			}
			set
			{
				if ((this._uses_database_collation != value))
				{
					this._uses_database_collation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_system_named", DbType="Bit NOT NULL")]
		public bool is_system_named
		{
			get
			{
				return this._is_system_named;
			}
			set
			{
				if ((this._is_system_named != value))
				{
					this._is_system_named = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.default_constraints")]
	public partial class default_constraint
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private int _parent_column_id;
		
		private string _definition;
		
		private bool _is_system_named;
		
		public default_constraint()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_column_id", DbType="Int NOT NULL")]
		public int parent_column_id
		{
			get
			{
				return this._parent_column_id;
			}
			set
			{
				if ((this._parent_column_id != value))
				{
					this._parent_column_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_definition", DbType="NVarChar(MAX)")]
		public string definition
		{
			get
			{
				return this._definition;
			}
			set
			{
				if ((this._definition != value))
				{
					this._definition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_system_named", DbType="Bit NOT NULL")]
		public bool is_system_named
		{
			get
			{
				return this._is_system_named;
			}
			set
			{
				if ((this._is_system_named != value))
				{
					this._is_system_named = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.triggers")]
	public partial class trigger
	{
		
		private string _name;
		
		private int _object_id;
		
		private byte _parent_class;
		
		private string _parent_class_desc;
		
		private int _parent_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_disabled;
		
		private bool _is_not_for_replication;
		
		private bool _is_instead_of_trigger;
		
		public trigger()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_class", DbType="TinyInt NOT NULL")]
		public byte parent_class
		{
			get
			{
				return this._parent_class;
			}
			set
			{
				if ((this._parent_class != value))
				{
					this._parent_class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_class_desc", DbType="NVarChar(60)")]
		public string parent_class_desc
		{
			get
			{
				return this._parent_class_desc;
			}
			set
			{
				if ((this._parent_class_desc != value))
				{
					this._parent_class_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this._parent_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_disabled", DbType="Bit NOT NULL")]
		public bool is_disabled
		{
			get
			{
				return this._is_disabled;
			}
			set
			{
				if ((this._is_disabled != value))
				{
					this._is_disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_not_for_replication", DbType="Bit NOT NULL")]
		public bool is_not_for_replication
		{
			get
			{
				return this._is_not_for_replication;
			}
			set
			{
				if ((this._is_not_for_replication != value))
				{
					this._is_not_for_replication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_instead_of_trigger", DbType="Bit NOT NULL")]
		public bool is_instead_of_trigger
		{
			get
			{
				return this._is_instead_of_trigger;
			}
			set
			{
				if ((this._is_instead_of_trigger != value))
				{
					this._is_instead_of_trigger = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.sql_modules")]
	public partial class sql_module
	{
		
		private int _object_id;
		
		private string _definition;
		
		private System.Nullable<bool> _uses_ansi_nulls;
		
		private System.Nullable<bool> _uses_quoted_identifier;
		
		private System.Nullable<bool> _is_schema_bound;
		
		private System.Nullable<bool> _uses_database_collation;
		
		private System.Nullable<bool> _is_recompiled;
		
		private System.Nullable<bool> _null_on_null_input;
		
		private System.Nullable<int> _execute_as_principal_id;
		
		public sql_module()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_definition", DbType="NVarChar(MAX)")]
		public string definition
		{
			get
			{
				return this._definition;
			}
			set
			{
				if ((this._definition != value))
				{
					this._definition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_ansi_nulls", DbType="Bit")]
		public System.Nullable<bool> uses_ansi_nulls
		{
			get
			{
				return this._uses_ansi_nulls;
			}
			set
			{
				if ((this._uses_ansi_nulls != value))
				{
					this._uses_ansi_nulls = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_quoted_identifier", DbType="Bit")]
		public System.Nullable<bool> uses_quoted_identifier
		{
			get
			{
				return this._uses_quoted_identifier;
			}
			set
			{
				if ((this._uses_quoted_identifier != value))
				{
					this._uses_quoted_identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_bound", DbType="Bit")]
		public System.Nullable<bool> is_schema_bound
		{
			get
			{
				return this._is_schema_bound;
			}
			set
			{
				if ((this._is_schema_bound != value))
				{
					this._is_schema_bound = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_database_collation", DbType="Bit")]
		public System.Nullable<bool> uses_database_collation
		{
			get
			{
				return this._uses_database_collation;
			}
			set
			{
				if ((this._uses_database_collation != value))
				{
					this._uses_database_collation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_recompiled", DbType="Bit")]
		public System.Nullable<bool> is_recompiled
		{
			get
			{
				return this._is_recompiled;
			}
			set
			{
				if ((this._is_recompiled != value))
				{
					this._is_recompiled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_null_on_null_input", DbType="Bit")]
		public System.Nullable<bool> null_on_null_input
		{
			get
			{
				return this._null_on_null_input;
			}
			set
			{
				if ((this._null_on_null_input != value))
				{
					this._null_on_null_input = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_execute_as_principal_id", DbType="Int")]
		public System.Nullable<int> execute_as_principal_id
		{
			get
			{
				return this._execute_as_principal_id;
			}
			set
			{
				if ((this._execute_as_principal_id != value))
				{
					this._execute_as_principal_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.views")]
	public partial class view
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _has_replication_filter;
		
		private bool _has_opaque_metadata;
		
		private bool _has_unchecked_assembly_data;
		
		private bool _with_check_option;
		
		private bool _is_date_correlation_view;
		
		public view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this._is_replicated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_replication_filter", DbType="Bit")]
		public System.Nullable<bool> has_replication_filter
		{
			get
			{
				return this._has_replication_filter;
			}
			set
			{
				if ((this._has_replication_filter != value))
				{
					this._has_replication_filter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_opaque_metadata", DbType="Bit NOT NULL")]
		public bool has_opaque_metadata
		{
			get
			{
				return this._has_opaque_metadata;
			}
			set
			{
				if ((this._has_opaque_metadata != value))
				{
					this._has_opaque_metadata = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_unchecked_assembly_data", DbType="Bit NOT NULL")]
		public bool has_unchecked_assembly_data
		{
			get
			{
				return this._has_unchecked_assembly_data;
			}
			set
			{
				if ((this._has_unchecked_assembly_data != value))
				{
					this._has_unchecked_assembly_data = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_with_check_option", DbType="Bit NOT NULL")]
		public bool with_check_option
		{
			get
			{
				return this._with_check_option;
			}
			set
			{
				if ((this._with_check_option != value))
				{
					this._with_check_option = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_date_correlation_view", DbType="Bit NOT NULL")]
		public bool is_date_correlation_view
		{
			get
			{
				return this._is_date_correlation_view;
			}
			set
			{
				if ((this._is_date_correlation_view != value))
				{
					this._is_date_correlation_view = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
