///////////////////////////////////////////////////////////
//  MessageType.cs
//  Implementation of the Class MessageType
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:49:01
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////




namespace EAAddIn {
	public struct MessageType {

        public  const string Warning = "Warning";
        public  const string Information = "Information";
        public  const string Error = "Error";
        public  const string Question = "Question";
	}//end MessageType

}//end namespace DatabaseReleaseManager