///////////////////////////////////////////////////////////
//  Connector.cs
//  Implementation of the Class Connector
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:48:51
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class Connector {

		/// 
		/// <param name="prefix"></param>
		public List<Connector> ListWithStereotypeStartingWith(string prefix){

			return null;
		}

		public bool Delete(){

			return false;
		}

		/// 
		/// <param name="release"></param>
		public List<Connector> ListWithStereotypeAfter(string release){

			return null;
		}

		public string Note{
			get;
			set;
		}

		public string Stereotype{
			get;
			set;
		}

		public bool Save(){

			return false;
		}

		public string PreviousName{
			get;
			set;
		}

		public string Name{
			get;
			set;
		}

	}//end Connector

}//end namespace DatabaseReleaseManager