///////////////////////////////////////////////////////////
//  DwefaultStereotypes.cs
//  Implementation of the Class DefaultStereotypes
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:48:54
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////




namespace EAAddIn.Applications.DatabaseReleaseManager
{
    public class DefaultStereotypes
    {
        public readonly string[] Defaults = new[] { "new column", "renamed column", "deleted column", "to be deleted column", "changed column", 
            "new table", "renamed table", "deleted table", "to be deleted table", "changed table" };
        public readonly string[] BaseStereotypes = new[] { "table", "column" };
    }//end DefaultStereotypes

}//end namespace DatabaseReleaseManager