///////////////////////////////////////////////////////////
//  Element.cs
//  Implementation of the Class Element
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:48:56
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class Element {

	    private EA.Element eaElement;
		/// 
		/// <param name="stereotypePrefix"></param>
		public List<string[]> ListContainingStereotype(string stereotypePrefix){

            return new EaAccess().ListClassesContainingStereotype("table " + stereotypePrefix);
		}

		public bool Delete(){

			return false;
		}

		/// 
		/// <param name="release"></param>
		public List<Element> ListWithStereotypeAfter(string release){

			return null;
		}

		public bool ManualCleanRequired{
			get;
			set;
		}

		public string Note{
			get;
			set;
		}

		public string Stereotype{
			get;
			set;
		}

		public bool Save(){

			return false;
		}

		public string PreviousName{
			get;
			set;
		}

        public string Name
        {
            get;
            set;
        }

        public string EaGuid
        {
            get;
            set;
        }
        public EA.Element EaElement
        {
            get
            {
                if (string.IsNullOrEmpty(EaGuid))
                    return null;
                
                if (eaElement == null)
                {
                    eaElement = AddInRepository.Instance.Repository.GetElementByGuid(EaGuid);
                }
                return eaElement;
            }
        }
	}//end Element

}//end namespace DatabaseReleaseManager