///////////////////////////////////////////////////////////
//  ReleaseStream.cs
//  Implementation of the Class ReleaseStream
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:49:06
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System.ComponentModel;

namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class ReleaseStream {

        public static BindingList<string> List()
		{
		    return new BindingList<string>{Release, Fix};
		}

        public string Name { get; set; }

        public const string Release = "Release";
        public const string Fix = "Fix";

	}//end ReleaseStream

}//end namespace DatabaseReleaseManager