///////////////////////////////////////////////////////////
//  StereotypeTypes.cs
//  Implementation of the Class StereotypeTypes
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:49:10
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////





namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class StereotypeTypes {

		private string Database = "DATABASE";

	}//end StereotypeTypes

}//end namespace DatabaseReleaseManager