///////////////////////////////////////////////////////////
//  Stereotype.cs
//  Implementation of the Class Stereotype
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:49:08
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class Stereotype {

		public string Name;

		/// 
		/// <param name="release"></param>
        public List<Message> CreateDatabaseStereotypes(string release)
		{

            var messages = new List<Message>();
		    var ea = new EaAccess();
		    
            messages.Add(ea.CreateStereotype("new column " + release, "attribtable"));
		    messages.Add(ea.CreateStereotype("deleted column " + release, "attribtable"));
		    messages.Add(ea.CreateStereotype("renamed column " + release, "attribtable"));
		    messages.Add(ea.CreateStereotype("changed column " + release, "attribtable"));

            messages.Add(ea.CreateStereotype("new column " + release, "attribute"));
            messages.Add(ea.CreateStereotype("deleted column " + release, "attribute"));
            messages.Add(ea.CreateStereotype("renamed column " + release, "attribute"));
            messages.Add(ea.CreateStereotype("changed column " + release, "attribute"));

            messages.Add(ea.CreateStereotype("new table " + release, "class"));
            messages.Add(ea.CreateStereotype("deleted table " + release, "class"));
            messages.Add(ea.CreateStereotype("renamed table " + release, "class"));
            messages.Add(ea.CreateStereotype("changed table " + release, "class"));

            return messages;
		}


        public List<Message> DeleteDatabaseStereotypes(string release)
        {

            var releaseToDeleteStereotypes = new Release {Name = release};
            var messages = releaseToDeleteStereotypes.ValidateOkToDelete();

            if (messages.Count == 0)
            {
                var ea = new EaAccess();

                messages.Add(ea.DeleteStereotype("new column " + release, "attribtable"));
                messages.Add(ea.DeleteStereotype("deleted column " + release, "attribtable"));
                messages.Add(ea.DeleteStereotype("renamed column " + release, "attribtable"));
                messages.Add(ea.DeleteStereotype("changed column " + release, "attribtable"));

                messages.Add(ea.DeleteStereotype("new column " + release, "attribute"));
                messages.Add(ea.DeleteStereotype("deleted column " + release, "attribute"));
                messages.Add(ea.DeleteStereotype("renamed column " + release, "attribute"));
                messages.Add(ea.DeleteStereotype("changed column " + release, "attribute"));

                messages.Add(ea.DeleteStereotype("new table " + release, "class"));
                messages.Add(ea.DeleteStereotype("deleted table " + release, "class"));
                messages.Add(ea.DeleteStereotype("renamed table " + release, "class"));
                messages.Add(ea.DeleteStereotype("changed table " + release, "class"));
            }
            return messages;
        }

	    /// 
		/// <param name="stereotype"></param>
		public bool DatabaseStereotypeExists(string stereotype){

			return false;
		}

	}//end Stereotype

}//end namespace DatabaseReleaseManager