///////////////////////////////////////////////////////////
//  DatabaseReleaseManagerMenu.cs
//  Implementation of the Class DatabaseReleaseManagerMenu
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 15:54:13
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System.Runtime.InteropServices;
using EAAddIn.Windows.Controls;

namespace EAAddIn.Menus {
	[ComVisible(false)]
	public class DatabaseReleaseManagerMenu : IEAMenu {



        public string Name
        {
            get { return AddInApplications.DBAReleaseManager; }
        }

        public List<string> SecurityRoles
        {
            get { return new List<string> { EASecurityGroups.DBA }; }
        }


		public void ActivateAddIn(){

            var drm = (DatabaseReleaseManagerControl)AddInRepository.Instance.Repository.AddTab("DB Release Manager", "EAAddIn.Windows.Controls.DatabaseReleaseManagerControl");
            //var drm = new DatabaseReleaseManagerFormUsingControl();
            //drm.Show();
		}

	}//end DatabaseReleaseManagerMenu

}//end namespace EAAddIn