///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:48:48
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace EAAddIn.Applications.DatabaseReleaseManager {
	public class Attribute {


		public List<string[]> ListContainingStereotype(string release){

            return new EaAccess().ListAttributesContainingStereotype("column " + release);

		}

	    public bool Delete(){

			return false;
		}

		public string Note{
			get;
			set;
		}

		public string Stereotype{
			get;
			set;
		}

		public bool Save(){

			return false;
		}

		public string PreviousName{
			get;
			set;
		}

		public string Name{
			get;
			set;
		}

	}//end Attribute

}//end namespace DatabaseReleaseManager