///////////////////////////////////////////////////////////
//  AuditDetail.cs
//  Implementation of the Class AuditDetail
//  Generated by Enterprise Architect
//  Created on:      15-Jul-2010 15:23:52
//  Original author: Wayne Lombard
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Xml.Linq;

namespace EAAddIn.Applications.AuditConverter
{

    public class AuditDetail
    {
        public string audit_id
        {
            get;
            set;
        }

        public string property
        {
            get;
            set;
        }

        public string old_value
        {
            get;
            set;
        }

        public string new_value
        {
            get;
            set;
        }



        public static List<AuditDetail> AddValues(List<BinContent1> binContent1List)
        {
            var auditDetails = new List<AuditDetail>();

            foreach (BinContent1 binContent1 in binContent1List)
            {
                var locAudit = new AuditDetail
                                   {
                                       audit_id = "1",
                                       property = binContent1.ColumnName,
                                       old_value = binContent1.ColumnOldValue,
                                       new_value = binContent1.ColumnNewValue
                                   };

                auditDetails.Add(locAudit);
            }
            return auditDetails;
        }
    }
}