///////////////////////////////////////////////////////////
//  IDatabaseReleaseManager.cs
//  Implementation of the Interface IDatabaseReleaseManager
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 15:52:41
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System;
using System.Windows.Forms;
using EAAddIn.Applications.DatabaseReleaseManager;

namespace EAAddIn.Windows.Interfaces {
	public interface IDatabaseReleaseManager {

		void Show();
	    event EventHandler<EventArgs> MaintainReleasesRequested;
        BindingSource MessagesBindingSource { get; set; }
	    BindingSource ReleasesBindingSource { get; }
	    string ReleasesDisplayMember { set; }
	    string ReleasesValueMember { set; }
        Object SelectedRelease { get; }
	    event EventHandler<EventArgs> CreateStereotypesRequested;
	    event EventHandler<EventArgs> CleanupEaRelease1Requested;
	    event EventHandler<EventArgs> CleanupEaDbRepositoryRequested;
        event EventHandler<EventArgs> ReleaseSelected;
	    void BindReleases();
	    void BindMessages();
	    event EventHandler<EventArgs> DeleteStereotypesRequested;
	    event EventHandler<EventArgs> PreviewMessagesReportRequested;
        event Message.MessagesHandler LocateInBrowserRequested;
        event Message.MessagesHandler ClearStereotypesRequested;
        event Message.MessagesHandler FindStereotypeUsageRequested;
    }//end IDatabaseReleaseManager

}//end namespace Interfaces