///////////////////////////////////////////////////////////
//  IMaintainReleases.cs
//  Implementation of the Interface IMaintainReleases
//  Generated by Enterprise Architect
//  Created on:      12-Nov-2009 10:21:34
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////


using System;
using System.Windows.Forms;
using EAAddIn.Applications.DatabaseReleaseManager;

public interface IMaintainReleases {

	void Show();
    BindingSource ReleasesBindingSource { get; set; }
    string ReleasesDisplayMember { set; }
    string ReleasesValueMember { set; }

    BindingSource StreamsBindingSource { get; }
    BindingSource MessagesBindingSource { get; set; }

    DateTime ReleaseDate { get; set; }
    string Stream { get; set; }
    object SelectedRelease { get; set; }
    string ReleaseName { get; set; }

    event EventHandler<EventArgs> ReleaseSelected;
    event EventHandler<EventArgs> NewReleaseRequested;
    event EventHandler<EventArgs> DeleteReleaseRequested;
    event EventHandler<EventArgs> SaveReleaseRequested;
    void BindData();

    bool ConfirmSave();

    void RestorePreviousReleaseSelection();
    void SaveEnabled(bool enabled);

    void BringToFront();
    event EventHandler<EventArgs> ReleaseFormClosed;
}//end IMaintainReleases