
    
	
    
		
//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;
using Employment.Esc.Framework.Communication.Behaviors;

namespace Employment.Esc.StreamServiceReview.Contracts.ServiceContracts
{
	[ServiceContract(Namespace = "http://employment.esc.contracts.StreamServiceReview/2009/03")]
	[AuthorisationContractBehavior]
	public partial interface IStreamServiceReview
	{
 	}
}
    
  