///////////////////////////////////////////////////////////
//  Message.cs
//  Implementation of the Class Message
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:48:59
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////




namespace EaAuditConverter.AuditScheduler
{
    public class Message
    {

        //public delegate void MessagesHandler(object sender, MessagesEventArgs e);

        private string type = string.Empty;

        public virtual string Type
        {
            get { return type; }
            set { type = value; }
        }
        public string Text { get; set; }
        public object Tag { get; set; }


    }

    public class InformationMessage : Message
    {
        public InformationMessage(string text)
        {
            Text = text;
        }
        public override string Type { get { return MessageType.Information; } }

    }

    public class ErrorMessage : Message
    {
        public ErrorMessage(string text)
        {
            Text = text;

        }
        public override string Type { get { return MessageType.Error; } }

    }

    public class ResultMessage : Message
    {
        public ResultMessage(string text)
        {
            Text = text;
        }
        public override string Type { get { return MessageType.Result; } }

    }
}