///////////////////////////////////////////////////////////
//  MessageType.cs
//  Implementation of the Class MessageType
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 16:49:01
//  Original author: Colin Richardson
///////////////////////////////////////////////////////////




namespace EaAuditConverter.AuditScheduler {
	public struct MessageType {
        public  const string Information = "Information";
        public const string Error = "Error";
        public const string Result = "Result";
	    public const string Console = "Console";
	}
}