//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ImageAbout {
            get {
                object obj = ResourceManager.GetObject("ImageAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageActivity {
            get {
                object obj = ResourceManager.GetObject("ImageActivity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageActivityDiagram {
            get {
                object obj = ResourceManager.GetObject("ImageActivityDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageActivityPartition {
            get {
                object obj = ResourceManager.GetObject("ImageActivityPartition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageActor {
            get {
                object obj = ResourceManager.GetObject("ImageActor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageActorNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageActorNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageASPpage {
            get {
                object obj = ResourceManager.GetObject("ImageASPpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageAttribute {
            get {
                object obj = ResourceManager.GetObject("ImageAttribute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageAttributeNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageAttributeNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageBoundary {
            get {
                object obj = ResourceManager.GetObject("ImageBoundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABApproved {
            get {
                object obj = ResourceManager.GetObject("ImageCABApproved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABChangesRequired {
            get {
                object obj = ResourceManager.GetObject("ImageCABChangesRequired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABImplemented {
            get {
                object obj = ResourceManager.GetObject("ImageCABImplemented", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageCABNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABProposed {
            get {
                object obj = ResourceManager.GetObject("ImageCABProposed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABToBeReviewed {
            get {
                object obj = ResourceManager.GetObject("ImageCABToBeReviewed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCABUnderDevelopment {
            get {
                object obj = ResourceManager.GetObject("ImageCABUnderDevelopment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCategory {
            get {
                object obj = ResourceManager.GetObject("ImageCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageClass {
            get {
                object obj = ResourceManager.GetObject("ImageClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageClassDiagram {
            get {
                object obj = ResourceManager.GetObject("ImageClassDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageClassNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageClassNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageCollaboration {
            get {
                object obj = ResourceManager.GetObject("ImageCollaboration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageComponent {
            get {
                object obj = ResourceManager.GetObject("ImageComponent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageDecision {
            get {
                object obj = ResourceManager.GetObject("ImageDecision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageElement {
            get {
                object obj = ResourceManager.GetObject("ImageElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageElementNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageElementNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageEvent {
            get {
                object obj = ResourceManager.GetObject("ImageEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageFragment {
            get {
                object obj = ResourceManager.GetObject("ImageFragment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageFunction {
            get {
                object obj = ResourceManager.GetObject("ImageFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageGreen {
            get {
                object obj = ResourceManager.GetObject("ImageGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageInteractionOccurrence {
            get {
                object obj = ResourceManager.GetObject("ImageInteractionOccurrence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageInterface {
            get {
                object obj = ResourceManager.GetObject("ImageInterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageNote {
            get {
                object obj = ResourceManager.GetObject("ImageNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageObject {
            get {
                object obj = ResourceManager.GetObject("ImageObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageOperation {
            get {
                object obj = ResourceManager.GetObject("ImageOperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageOrange {
            get {
                object obj = ResourceManager.GetObject("ImageOrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImagePackage {
            get {
                object obj = ResourceManager.GetObject("ImagePackage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImagePackageNotFound {
            get {
                object obj = ResourceManager.GetObject("ImagePackageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageQuestionMark {
            get {
                object obj = ResourceManager.GetObject("ImageQuestionMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageRed {
            get {
                object obj = ResourceManager.GetObject("ImageRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageRequirement {
            get {
                object obj = ResourceManager.GetObject("ImageRequirement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageRequirement1 {
            get {
                object obj = ResourceManager.GetObject("ImageRequirement1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageRequirementNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageRequirementNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageRootModel {
            get {
                object obj = ResourceManager.GetObject("ImageRootModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageScreen {
            get {
                object obj = ResourceManager.GetObject("ImageScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageScreenNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageScreenNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageSequenceDiagram {
            get {
                object obj = ResourceManager.GetObject("ImageSequenceDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageStoredProcedure {
            get {
                object obj = ResourceManager.GetObject("ImageStoredProcedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageTable {
            get {
                object obj = ResourceManager.GetObject("ImageTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageTableNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageTableNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageText {
            get {
                object obj = ResourceManager.GetObject("ImageText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageUIDiagram {
            get {
                object obj = ResourceManager.GetObject("ImageUIDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageUseCase {
            get {
                object obj = ResourceManager.GetObject("ImageUseCase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageUseCaseDiagram {
            get {
                object obj = ResourceManager.GetObject("ImageUseCaseDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageUseCaseNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageUseCaseNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageView {
            get {
                object obj = ResourceManager.GetObject("ImageView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewSQL {
            get {
                object obj = ResourceManager.GetObject("ImageViewSQL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageWhite {
            get {
                object obj = ResourceManager.GetObject("ImageWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
