
//------------------------------------------------------------------------------
// <auto-generated>
  //
  //     This code was generated by Code Generator for
  //     Wrapper        : StreamServiceReview
  //     Generated User : WL0035
  //     Generated Date : 15:43:22 03 June 2009
  //     Runtime Version: 1.0.0.0
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  //
  //
//</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;
using Employment.Esc.Shared.Contracts.Execution;
using Employment.Esc.Shared.Contracts;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace Employment.Esc.StreamServiceReview.Contracts.DataContracts
{
	[DataContract(Namespace = "http://employment.esc.contracts/2009/03")]
	public class ssrDetailsReadRequest
    {
		[NotNullValidator(MessageTemplate = "JobseekerId is Mandatory Field")]
		[FieldAlias("jobseekerId")]
		[DataMember]
		public long?  JobseekerId
		{
			get;
			set;
		}
        [NotNullValidator(MessageTemplate = "ReviewSeqNum is Mandatory Field")]
		[FieldAlias("reviewSeqNum")]
		[DataMember]
		public int?  ReviewSeqNum
		{
			get;
			set;
		}
        
    }
}
  